# Generated by Django 5.2.17 on 2026-10-03 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_product_height_cm_product_length_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=7, help_text='Typical days from placing a purchase order to receiving it.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=620)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='inv_poitem_exactly_one_target')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(max_length=620)),
                ('movement_type', models.CharField(choices=[('initial', 'Initial stock'), ('purchase_receipt', 'Purchase receipt'), ('sale', 'Sale'), ('order_cancel', 'Order cancelled (restock)'), ('return', 'Customer return'), ('adjustment', 'Manual adjustment'), ('damage', 'Damaged / expired / lost'), ('stocktake', 'Stocktake correction'), ('external', 'Edited outside inventory (admin/API/import)')], db_index=True, max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive = stock in, negative = stock out.')),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Order number, purchase order number, etc.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='inventory_s_variant_608d8a_idx'), models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='At or below this quantity the item is flagged as low stock.')),
                ('reorder_quantity', models.PositiveIntegerField(default=0, help_text='Suggested quantity to order when restocking (0 = no suggestion).')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_policy', to='catalog.product')),
                ('variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_policy', to='catalog.productvariant')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Stock policy',
                'verbose_name_plural': 'Stock policies',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='inv_policy_exactly_one_target')],
            },
        ),
    ]
