# Generated by Django 5.2.17 on 2026-10-02 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Internal label shown in the admin list — not necessarily displayed on the site.', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(help_text='Primary banner image (desktop/default).', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional alternate image for small screens. Falls back to `image` if not set.', null=True, upload_to='banners/mobile/')),
                ('link_url', models.URLField(blank=True, help_text='Where the banner navigates to when clicked. Leave blank for a non-clickable banner.', max_length=500)),
                ('cta_text', models.CharField(blank=True, help_text="Call-to-action label, e.g. 'Shop Now'. Only meaningful if link_url is set.", max_length=100)),
                ('placement', models.CharField(choices=[('home_hero', 'Home — Hero'), ('home_promo', 'Home — Secondary Promo')], db_index=True, default='home_hero', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='Optional. Banner is hidden before this time if set.', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='Optional. Banner is hidden after this time if set.', null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['placement', 'sort_order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='dashboard_b_placeme_d67926_idx'), models.Index(fields=['sort_order'], name='dashboard_b_sort_or_743d37_idx')],
            },
        ),
    ]
