# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_for',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Bullet list shown under 'Recommended For', e.g. "
                    '["Dull Skin", "Hyper Pigmentation", "Uneven Skin Tone"]'
                ),
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='good_to_know',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Bullet list shown under 'Good To Know', e.g. "
                    '["pH: 4.8", "Vegan, Cruelty-Free", "For All Skin-Types"]'
                ),
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(
                blank=True,
                help_text="Content for the 'Ingredients' tab on the product page.",
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(
                blank=True,
                help_text="Content for the 'Usage' tab on the product page (how to use).",
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='faqs',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Content for the 'FAQ' tab. List of objects, e.g. "
                    '[{"question": "Is this vegan?", "answer": "Yes, fully vegan."}]'
                ),
            ),
        ),
    ]
