# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_faq_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_title',
            field=models.CharField(
                blank=True,
                max_length=300,
                help_text=(
                    "Heading shown above the About tab's description, e.g. "
                    "'A boost of anti-oxidant rich nourishing renewal for dull, "
                    "dry and tired skin.'"
                ),
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_title',
            field=models.CharField(
                blank=True,
                max_length=300,
                help_text="Heading shown above the Ingredients tab's content.",
            ),
        ),
    ]
