# Generated by Django 4.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_tab_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about_title',
            field=models.CharField(
                blank=True,
                max_length=300,
                help_text=(
                    "Small caption/overline shown directly above the About "
                    "tab's description, e.g. 'ABOUT THE PRODUCT'."
                ),
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='about_heading',
            field=models.CharField(
                blank=True,
                max_length=500,
                help_text=(
                    "Large heading statement for the product (shown in the "
                    "page's hero/summary section), e.g. 'A boost of "
                    "anti-oxidant rich nourishing renewal for dull, dry and "
                    "tired skin.'"
                ),
            ),
        ),
    ]
