# Generated by Django 5.2.17 on 2026-10-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_about_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packaged height in centimeters. Used for shipping when this product has no variants.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packaged length in centimeters. Used for shipping when this product has no variants.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock for this product. Only used while the product has no variants — once variants exist, stock is tracked per-variant instead and this field is ignored.'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kilograms. Used for shipping when this product has no variants.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packaged width/breadth in centimeters. Used for shipping when this product has no variants.', max_digits=6, null=True),
        ),
    ]
