# Generated by Django 4.2.13 on 2026-07-29 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cart subtotal must be >= this amount for the coupon to apply.', max_digits=12, null=True)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps the discount amount. Mainly relevant for percentage coupons.', max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon may be used, across all users. Blank = unlimited.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Times a single user/guest may use this coupon. Blank = unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed', models.BooleanField(default=False, help_text='True once an order using this coupon has actually been placed.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='cart.cart')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
